
  apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
       env:
      - name: passoword
        valueFrom:
          secretKeyRef:
            name: mysqlsecret
            key: password
        ports:
        - containerPort: 3306
          name: mysql
